name: Labels Create

on:
  workflow_call:
    inputs:
      owner:
        description: 'GitHub organization or user that owns the repository'
        type: string
      repo:
        description: 'GitHub repository name (if not the current repository)'
        type: string
      dry-run:
        description: 'Dry run'
        type: boolean
      update-existing:
        description: 'Whether to update existing labels (e.g. rename, change color/description).'
        type: boolean
      ref:
        description: 'Git ref of the shared actions repo to use (e.g. main or a specific tag/commit)'
        type: string
    secrets:
      github-token:
        description: 'GitHub token for authentication'
        required: false

  workflow_dispatch:
    inputs:
      owner:
        description: 'GitHub organization or user that owns the repository'
        type: string
      repo:
        description: 'GitHub repository name (if not the current repository)'
        type: string
      dry-run:
        description: 'Dry run'
        type: boolean
        default: true
      update-existing:
        description: 'Whether to update existing labels (e.g. rename, change color/description).'
        type: boolean
      ref:
        description: 'Git ref of the shared actions repo to use (e.g. main or a specific tag/commit)'
        type: string

  workflow_run:
    workflows: ['_']
    types: [completed]

jobs:
  create-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Checkout shared actions repo
        if: inputs.ref != ''
        uses: actions/checkout@v6
        with:
          repository: stairwaytowonderland/actions
          ref: ${{ inputs.ref }}
          path: ./.actions
          sparse-checkout: |
            .github

      - name: Create labels (with specified actions ref)
        if: inputs.ref != ''
        uses: ./.actions/.github/actions/labels-create-action
        with:
          github-token: ${{ secrets.github-token || secrets.GITHUB_TOKEN }}
          owner: ${{ inputs.owner || '' }}
          repo: ${{ inputs.repo || '' }}
          dry-run: ${{ inputs.dry-run == true }}
          update-existing: ${{ inputs.update-existing == true }}

      - name: Create labels (with default actions ref)
        if: inputs.ref == ''
        uses: stairwaytowonderland/actions/.github/actions/labels-create-action@v1
        with:
          github-token: ${{ secrets.github-token || secrets.GITHUB_TOKEN }}
          owner: ${{ inputs.owner || '' }}
          repo: ${{ inputs.repo || '' }}
          dry-run: ${{ inputs.dry-run == true }}
          update-existing: ${{ inputs.update-existing == true }}
